<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <AssemblyName>Orc.Extensibility.Example.ExtensionA</AssemblyName>
    <RootNamespace>Orc.Extensibility.Example</RootNamespace>
    <DefaultLanguage>en-US</DefaultLanguage>
    <SonarQubeExclude>true</SonarQubeExclude>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <UseWpf>true</UseWpf>
    <OutputType>Library</OutputType>
    <StartupObject />
    <NoWarn>$(NoWarn);SA1652</NoWarn>
    <ApplicationIcon />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Catel.Fody" Version="7.0.0" PrivateAssets="all" />
    <PackageReference Include="Catel.SourceGenerators" Version="7.0.1" PrivateAssets="all" />
    <PackageReference Include="Costura.Fody" Version="6.1.0" PrivateAssets="all" />
    <PackageReference Include="EntityFramework" Version="6.5.2" />
    <PackageReference Include="Fody" Version="6.9.3" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" PrivateAssets="all" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" PrivateAssets="all" />
    <PackageReference Include="Orc.Controls" Version="6.0.0-alpha0120" />
    <PackageReference Include="Orc.Search.Xaml" Version="6.0.0-alpha0091" PrivateAssets="all" />
    <PackageReference Include="Orchestra.Core" Version="8.0.0-alpha0115" />
    <PackageReference Include="YamlDotNet" Version="17.1.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orc.Extensibility.Example.Api\Orc.Extensibility.Example.Api.csproj" />
  </ItemGroup>

  <Import Project="$(MSBuildProjectDirectory)\..\Directory.Build.shared.explicit.props" Condition="Exists('$(MSBuildProjectDirectory)\..\Directory.Build.shared.explicit.props')" />
  <Import Project="$(MSBuildProjectDirectory)\..\Directory.Build.shared.plugins.props" Condition="Exists('$(MSBuildProjectDirectory)\..\Directory.Build.shared.plugins.props')" />
</Project>
