//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("WildGums")]
[assembly: AssemblyVersion("3.2.1")]
[assembly: AssemblyFileVersion("3.2.1")]
[assembly: AssemblyInformationalVersion("3.2.1-alpha.1")]
[assembly: AssemblyCopyright("Copyright © WildGums 2010 - 2019")]

